#### 1. Identique as variáveis categóricas na base de dados e descreva como transformar apropriadamente cada uma delas para a regressão linear múltipla.

In [109]:
import pandas as pd

data = pd.read_csv("train.csv")
cat = []

print("Variaveis categoricas") 

for colum in data.columns:
    if data[colum].dtype == "object":
        cat.append(colum)

pd.DataFrame(cat, columns=["Categoricas"])

Variaveis categoricas

      Categoricas
0        MSZoning
1          Street
2           Alley
3        LotShape
4     LandContour
5       Utilities
6       LotConfig
7       LandSlope
8    Neighborhood
9      Condition1
10     Condition2
11       BldgType
12     HouseStyle
13      RoofStyle
14       RoofMatl
15    Exterior1st
16    Exterior2nd
17     MasVnrType
18      ExterQual
19      ExterCond
20     Foundation
21       BsmtQual
22       BsmtCond
23   BsmtExposure
24   BsmtFinType1
25   BsmtFinType2
26        Heating
27      HeatingQC
28     CentralAir
29     Electrical
30    KitchenQual
31     Functional
32    FireplaceQu
33     GarageType
34   GarageFinish
35     GarageQual
36     GarageCond
37     PavedDrive
38         PoolQC
39          Fence
40    MiscFeature
41       SaleType
42  SaleCondition

In [110]:
reference = ["MSZoning", "Street", "Alley", "LotShape", "LandContour", "Utilities", "LotConfig", "LandSlope", "Neighborhood", "Condition1", "Condition2",
             "BldgType", "HouseStyle", "RoofStyle", "RoofMatl", "Exterior1st", "Exterior2nd", "MasVnrType", "Foundation", "Heating", "CentralAir", "Electrical", 
             "GarageType", "GarageFinish", "PavedDrive", "MiscFeature", "SaleType", "SaleCondition"]
ordinal = ["ExterQual", "ExterCond", "BsmtQual", "BsmtCond", "BsmtExposure", "BsmtFinType1", "BsmtFinType2", "HeatingQC", "KitchenQual", "Functional",
           "FireplaceQu", "GarageQual", "GarageCond", "PoolQC", "Fence"]

#### 2. Crie uma nova versão do conjunto de treino com os atributos numéricos originais e com os categóricos convertidos adequadamente para numéricos.

In [111]:
data_references = data[reference]
data_ordinal = data[ordinal]

<p>COLUNAS COM VALORES NULOS EM data_references

In [112]:
data_references.isnull().sum().sort_values(ascending=False)

MiscFeature      1406
Alley            1369
GarageFinish       81
GarageType         81
MasVnrType          8
Electrical          1
MSZoning            0
Exterior1st         0
SaleType            0
PavedDrive          0
CentralAir          0
Heating             0
Foundation          0
Exterior2nd         0
RoofMatl            0
Street              0
RoofStyle           0
HouseStyle          0
BldgType            0
Condition2          0
Condition1          0
Neighborhood        0
LandSlope           0
LotConfig           0
Utilities           0
LandContour         0
LotShape            0
SaleCondition       0
dtype: int64

<p>Tratar Electrical (apenas 1 exemplo com valor nan). 
Os demais valores nan dizem respeito a falta do resurso na casa (ex. Alley = nan quer dizer que não tem beco de acesso a propriedade)

In [113]:
data_references.Electrical.value_counts()

SBrkr    1334
FuseA      94
FuseF      27
FuseP       3
Mix         1
Name: Electrical, dtype: int64

<p>Subistituir o nan por SBrkr (o valor mais frequente)

In [114]:
data_references.Electrical.fillna("SBrkr", inplace=True)
data_references.Electrical.value_counts()

C:\Users\david\AppData\Local\Temp\ipykernel_14152\3902909847.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_references.Electrical.fillna("SBrkr", inplace=True)

SBrkr    1335
FuseA      94
FuseF      27
FuseP       3
Mix         1
Name: Electrical, dtype: int64

<p>Transformando as variaveis categoricas atraves da codificação por referência

In [115]:
train = pd.get_dummies(data, columns=reference , drop_first=True)

<p>Transformando as variaveis categoricas em ordinais

<p>Realizando o mapeamento dos valores das variaveis

In [116]:
import numpy as np
map = [
        {'col':'PoolQC', 
        'mapping':{np.nan: 0, 'Fa':1, 'TA':2, 'Gd':3, 'Ex':4}},
        {'col':'Fence',
        'mapping':{np.nan: 0, 'MnWw':1, 'GdWo':2, 'MnPrv':3, 'GdPrv':4}},
        {'col':'FireplaceQu',
        'mapping':{np.nan: 0, 'Po':1, 'Fa':2, 'TA':3, 'Gd':4, 'Ex':5}},
        {'col':'GarageQual',
        'mapping':{np.nan: 0, 'Po':1, 'Fa':2, 'TA':3, 'Gd':4, 'Ex':5}},
        {'col':'GarageCond',
        'mapping':{np.nan: 0, 'Po':1, 'Fa':2, 'TA':3, 'Gd':4, 'Ex':5}},
        {'col':'BsmtExposure',
        'mapping':{np.nan: 0, 'No':1, 'Mn':2, 'Av':3, 'Gd':4}},
        {'col':'BsmtFinType2',
        'mapping':{np.nan: 0, 'Unf':1, 'LwQ':2, 'Rec':3, 'BLQ':4, 'ALQ':5, 'GLQ':6}},
        {'col':'BsmtQual',
        'mapping':{np.nan: 0, 'Po':1, 'Fa':2, 'TA':3, 'Gd':4, 'Ex':5}},
        {'col':'BsmtCond',
        'mapping':{np.nan: 0, 'Po':1, 'Fa':2, 'TA':3, 'Gd':4, 'Ex':5}},
        {'col':'BsmtFinType1',
        'mapping':{np.nan: 0, 'Unf':1, 'LwQ':2, 'Rec':3, 'BLQ':4, 'ALQ':5, 'GLQ':6}}, 
        {'col':'ExterQual',
        'mapping':{np.nan: 0, 'Po':1, 'Fa':2, 'TA':3, 'Gd':4, 'Ex':5}},  
        {'col':'ExterCond',
        'mapping':{np.nan: 0, 'Po':1, 'Fa':2, 'TA':3, 'Gd':4, 'Ex':5}},
        {'col':'HeatingQC',
        'mapping':{np.nan: 0, 'Po':1, 'Fa':2, 'TA':3, 'Gd':4, 'Ex':5}},
        {'col':'KitchenQual',
        'mapping':{np.nan: 0, 'Po':1, 'Fa':2, 'TA':3, 'Gd':4, 'Ex':5}},
        {'col':'Functional',
        'mapping':{'Typ':0, 'Min1':1, 'Min2':2, 'Mod':3, 'Maj1':4, 'Maj2':5, 'Sev':4, 'Sal':5}}
        ]

<p>Transformando as colunas de data_ordinal para ordinais

In [117]:
from category_encoders import OrdinalEncoder

ordinal_enc = OrdinalEncoder(mapping = map)
train = ordinal_enc.fit_transform(train)

<p>Conjunto de treino com os valores convertidos

In [118]:
train

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,ExterQual,...,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1,60,65.0,8450,7,5,2003,2003,196.0,4,...,0,0,0,0,1,0,0,0,1,0
1,2,20,80.0,9600,6,8,1976,1976,0.0,3,...,0,0,0,0,1,0,0,0,1,0
2,3,60,68.0,11250,7,5,2001,2002,162.0,4,...,0,0,0,0,1,0,0,0,1,0
3,4,70,60.0,9550,7,5,1915,1970,0.0,3,...,0,0,0,0,1,0,0,0,0,0
4,5,60,84.0,14260,8,5,2000,2000,350.0,4,...,0,0,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,62.0,7917,6,5,1999,2000,0.0,3,...,0,0,0,0,1,0,0,0,1,0
1456,1457,20,85.0,13175,6,6,1978,1988,119.0,3,...,0,0,0,0,1,0,0,0,1,0
1457,1458,70,66.0,9042,7,9,1941,2006,0.0,5,...,0,0,0,0,1,0,0,0,1,0
1458,1459,20,68.0,9717,5,6,1950,1996,0.0,3,...,0,0,0,0,1,0,0,0,1,0
1459,1460,20,75.0,9937,5,6,1965,1965,0.0,4,...,0,0,0,0,1,0,0,0,1,0

#### 3. Utilizando as conversões definidas para o conjunto de treino, converta o conjunto de teste da mesma forma.

In [119]:
test = pd.read_csv("test.csv")

test_references = test[reference]
test_ordinal = test[ordinal]

In [120]:
test_references.isnull().sum().sort_values(ascending=False)

MiscFeature      1408
Alley            1352
GarageFinish       78
GarageType         76
MasVnrType         16
MSZoning            4
Utilities           2
Exterior1st         1
SaleType            1
Exterior2nd         1
PavedDrive          0
Electrical          0
CentralAir          0
Heating             0
Foundation          0
RoofMatl            0
Street              0
RoofStyle           0
HouseStyle          0
BldgType            0
Condition2          0
Condition1          0
Neighborhood        0
LandSlope           0
LotConfig           0
LandContour         0
LotShape            0
SaleCondition       0
dtype: int64

<p>Convertendo os valores nan das colunas MSZoning, Utilities, Exterior1st, SaleType e Exterior2nd pelos valores mais frequentes

In [121]:
nan_cols = ['MSZoning', 'Utilities', 'Exterior1st']

for i in nan_cols:
    print(test_references[i].value_counts())

RL         1114
RM          242
FV           74
C (all)      15
RH           10
Name: MSZoning, dtype: int64
AllPub    1457
Name: Utilities, dtype: int64
VinylSd    510
MetalSd    230
HdBoard    220
Wd Sdng    205
Plywood    113
CemntBd     65
BrkFace     37
WdShing     30
AsbShng     24
Stucco      18
BrkComm      4
AsphShn      1
CBlock       1
Name: Exterior1st, dtype: int64

In [122]:
nan_cols = ['SaleType', 'Exterior2nd']

for i in nan_cols:
    print(test_references[i].value_counts())

WD       1258
New       117
COD        44
ConLD      17
CWD         8
Oth         4
ConLI       4
Con         3
ConLw       3
Name: SaleType, dtype: int64
VinylSd    510
MetalSd    233
HdBoard    199
Wd Sdng    194
Plywood    128
CmentBd     66
Wd Shng     43
BrkFace     22
Stucco      21
AsbShng     18
Brk Cmn     15
ImStucc      5
CBlock       2
AsphShn      1
Stone        1
Name: Exterior2nd, dtype: int64

In [123]:
test_references.MSZoning.fillna("RL", inplace=True)
test_references.Utilities.fillna("AllPub", inplace=True)
test_references.Exterior1st.fillna("VinylSd", inplace=True)
test_references.SaleType.fillna("WD", inplace=True)
test_references.Exterior2nd.fillna("VinylSd", inplace=True)

C:\Users\david\AppData\Local\Temp\ipykernel_14152\3480496490.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_references.MSZoning.fillna("RL", inplace=True)
C:\Users\david\AppData\Local\Temp\ipykernel_14152\3480496490.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_references.Utilities.fillna("AllPub", inplace=True)
C:\Users\david\AppData\Local\Temp\ipykernel_14152\3480496490.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_references.Exterior1st.fillna("VinylSd", inplace=True)
C:\Users\david\AppData\Local\Temp\ipykernel_14152\3480496490.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_references.SaleType.fillna("WD", inplace=True)
C:\Users\david\AppData\Local\Temp\ipykernel_14152\3480496490.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_references.Exterior2nd.fillna("VinylSd", inplace=True)

<p>Transformando as variaveis categoricas atraves da codificação por referência

In [124]:
test = pd.get_dummies(test, columns=reference , drop_first=True)
test

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,ExterQual,...,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1461,20,80.0,11622,5,6,1961,1961,0.0,TA,...,0,0,0,0,1,0,0,0,1,0
1,1462,20,81.0,14267,6,6,1958,1958,108.0,TA,...,0,0,0,0,1,0,0,0,1,0
2,1463,60,74.0,13830,5,5,1997,1998,0.0,TA,...,0,0,0,0,1,0,0,0,1,0
3,1464,60,78.0,9978,6,6,1998,1998,20.0,TA,...,0,0,0,0,1,0,0,0,1,0
4,1465,120,43.0,5005,8,5,1992,1992,0.0,Gd,...,0,0,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,21.0,1936,4,7,1970,1970,0.0,TA,...,0,0,0,0,1,0,0,0,1,0
1455,2916,160,21.0,1894,4,5,1970,1970,0.0,TA,...,0,0,0,0,1,0,0,0,0,0
1456,2917,20,160.0,20000,5,7,1960,1996,0.0,TA,...,0,0,0,0,1,0,0,0,0,0
1457,2918,85,62.0,10441,5,5,1992,1992,0.0,TA,...,0,0,0,0,1,0,0,0,1,0
1458,2919,60,74.0,9627,7,5,1993,1994,94.0,TA,...,0,0,0,0,1,0,0,0,1,0

<p>Transformando as variaveis categoricas em ordinais

In [125]:
test = ordinal_enc.fit_transform(test)

In [126]:
test

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,ExterQual,...,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1461,20,80.0,11622,5,6,1961,1961,0.0,3,...,0,0,0,0,1,0,0,0,1,0
1,1462,20,81.0,14267,6,6,1958,1958,108.0,3,...,0,0,0,0,1,0,0,0,1,0
2,1463,60,74.0,13830,5,5,1997,1998,0.0,3,...,0,0,0,0,1,0,0,0,1,0
3,1464,60,78.0,9978,6,6,1998,1998,20.0,3,...,0,0,0,0,1,0,0,0,1,0
4,1465,120,43.0,5005,8,5,1992,1992,0.0,4,...,0,0,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,21.0,1936,4,7,1970,1970,0.0,3,...,0,0,0,0,1,0,0,0,1,0
1455,2916,160,21.0,1894,4,5,1970,1970,0.0,3,...,0,0,0,0,1,0,0,0,0,0
1456,2917,20,160.0,20000,5,7,1960,1996,0.0,3,...,0,0,0,0,1,0,0,0,0,0
1457,2918,85,62.0,10441,5,5,1992,1992,0.0,3,...,0,0,0,0,1,0,0,0,1,0
1458,2919,60,74.0,9627,7,5,1993,1994,94.0,3,...,0,0,0,0,1,0,0,0,1,0

In [127]:
extra = train.columns.drop(test.columns)
extra

Index(['SalePrice', 'Utilities_NoSeWa', 'Condition2_RRAe', 'Condition2_RRAn',
       'Condition2_RRNn', 'HouseStyle_2.5Fin', 'RoofMatl_CompShg',
       'RoofMatl_Membran', 'RoofMatl_Metal', 'RoofMatl_Roll',
       'Exterior1st_ImStucc', 'Exterior1st_Stone', 'Exterior2nd_Other',
       'Heating_GasA', 'Heating_OthW', 'Electrical_Mix', 'MiscFeature_TenC'],
      dtype='object')

In [128]:
d = dict.fromkeys(extra.drop("SalePrice"), 0)
test = test.assign(**d)

In [129]:
test

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,ExterQual,...,RoofMatl_Membran,RoofMatl_Metal,RoofMatl_Roll,Exterior1st_ImStucc,Exterior1st_Stone,Exterior2nd_Other,Heating_GasA,Heating_OthW,Electrical_Mix,MiscFeature_TenC
0,1461,20,80.0,11622,5,6,1961,1961,0.0,3,...,0,0,0,0,0,0,0,0,0,0
1,1462,20,81.0,14267,6,6,1958,1958,108.0,3,...,0,0,0,0,0,0,0,0,0,0
2,1463,60,74.0,13830,5,5,1997,1998,0.0,3,...,0,0,0,0,0,0,0,0,0,0
3,1464,60,78.0,9978,6,6,1998,1998,20.0,3,...,0,0,0,0,0,0,0,0,0,0
4,1465,120,43.0,5005,8,5,1992,1992,0.0,4,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,21.0,1936,4,7,1970,1970,0.0,3,...,0,0,0,0,0,0,0,0,0,0
1455,2916,160,21.0,1894,4,5,1970,1970,0.0,3,...,0,0,0,0,0,0,0,0,0,0
1456,2917,20,160.0,20000,5,7,1960,1996,0.0,3,...,0,0,0,0,0,0,0,0,0,0
1457,2918,85,62.0,10441,5,5,1992,1992,0.0,3,...,0,0,0,0,0,0,0,0,0,0
1458,2919,60,74.0,9627,7,5,1993,1994,94.0,3,...,0,0,0,0,0,0,0,0,0,0

#### 4. Realize as previsões para o conjunto de teste

In [130]:
from sklearn.linear_model import LinearRegression

sp = train["SalePrice"].values

sp

train[train.columns[train.isnull().any()]]

      LotFrontage  MasVnrArea  GarageYrBlt
0            65.0       196.0       2003.0
1            80.0         0.0       1976.0
2            68.0       162.0       2001.0
3            60.0         0.0       1998.0
4            84.0       350.0       2000.0
...           ...         ...          ...
1455         62.0         0.0       1999.0
1456         85.0       119.0       1978.0
1457         66.0         0.0       1941.0
1458         68.0         0.0       1950.0
1459         75.0         0.0       1965.0

[1460 rows x 3 columns]

In [131]:
x1 = train['LotFrontage'].median()
x2 = train['MasVnrArea'].median()
x3 = train['GarageYrBlt'].median()

medianas = {"LotFrontage": x1, "MasVnrArea": x2, "GarageYrBlt": x3}

train = train.fillna(value=medianas)

In [132]:
test[test.columns[test.isnull().any()]]

x1 = train['LotFrontage'].median()
x2 = train['MasVnrArea'].median()
x3 = train['BsmtFinSF1'].median()
x4 = train['BsmtFinSF2'].median()
x5 = train['BsmtUnfSF'].median()
x6 = train['TotalBsmtSF'].median()
x7 = train['BsmtFullBath'].median()
x8 = train['BsmtHalfBath'].median()
x9 = train['GarageYrBlt'].median()
x10 = train['GarageCars'].median()
x11= train['GarageArea'].median()

medianas_test = {"LotFrontage": x1, "MasVnrArea": x2, "BsmtFinSF1": x3, "BsmtFinSF2": x4, "BsmtUnfSF": x5, "TotalBsmtSF": x6, "BsmtFullBath": x7, "BsmtHalfBath": x8, "GarageYrBlt": x9, "GarageCars": x10, "GarageArea": x11,}

test = test.fillna(value=medianas_test)

train = train.drop(["SalePrice"], axis=1)

In [133]:
model = LinearRegression()
model.fit(train, sp)

predict = model.predict(test)

c:\Users\david\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names must be in the same order as they were in fit.

  warnings.warn(message, FutureWarning)

TypeError: 'LinearRegression' object is not callable

#### 5. Avalie o RMSE e o R2 do conjunto de treino convertido utilizando 10-fold cross validation.

In [ ]:
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

kf = KFold(n_splits=10, shuffle=True, random_state=2)

sp = sp[:-1]; sp

for train_index, test_index in kf.split(sp):
    sp_train, sp_test = sp[train_index], sp[test_index]
    predict_train, predict_test = predict[train_index], predict[test_index]

rmse2 = np.sqrt(mean_squared_error(sp_train, predict_train))
print(f'RMSE: {rmse2:.0f}')

r3 = r2_score(sp_train, predict_train)
print(f'R2: {r3:.4f}')

RMSE: 569294
R2: -49.2853

#### 6. Faça o mesmo da questão anterior utilizando regressão passo-a-passo.

In [134]:
from dmba import AIC_score
from dmba import stepwise_selection

def score_model(model):
    if len(train) == 0:
        return AIC_score(sp, [sp.mean()] * len(sp), model, df=1)
    return AIC_score(sp, model.predict(train), model)

best_model, best_variables = stepwise_selection(train.columns, model, score_model(model), verbose=True)

for name, coef in zip(best_variables, best_model.coef_):
    print(f' {name}: {coef}')

TypeError: 'LinearRegression' object is not callable

#### 7. Faça o mesmo da questão anterior utilizando regressão com seleção progressiva.

#### 8. Faça o mesmo da questão anterior utilizando regressão com eliminação regressiva.

#### 9. Faça o mesmo da questão anterior utilizando o modelo GAM de regressão não linear.